services:
  cdr-generator:
    build: .
    image: ddcj/cdr-generator:v2
    container_name: cdr-generator
    ports:
      - "8501:8501"
    volumes:
      - /home/jeth/Projects/OMEA/POC/Poc_rfp_omea/cdr_generator/scripts/cdr_data:/app/cdr_data
    environment:
      - PYTHONUNBUFFERED=1
      - SFTP_HOST=sftp
      - SFTP_USER=foo
      - SFTP_PASS=pass
      - SFTP_PATH=/upload
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/"]
      interval: 30s
      timeout: 3s
      retries: 3



  sftp:
      image: atmoz/sftp:debian
      command: foo:pass:::upload




  nifi:
    image: apache/nifi:2.7.1
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      NIFI_WEB_HTTPS_PORT: 8443
    volumes:
      - /home/jeth/Projects/OMEA/POC/Poc_rfp_omea/cdr_generator/scripts/cdr_data:/opt/nifi/nifi-data/cdr_data


## docker logs nifi | grep Generated
## cf64ca55-213a-4f34-9151-d32882876ee4
## 65mFMOpSH9wHJKxxfe1v69Cs9MM3Mjjq


  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk