services:

## The MinIO service acts as the S3-compatible object storage for Iceberg tables.
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    networks:
      iceberg_net:
        aliases:
          - warehouse.minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
  
  ## The MinIO Client (mc) service is used to set up the initial bucket and policies in MinIO.
  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      iceberg_net:
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: |
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc mb minio/datalake;
      /usr/bin/mc policy set public minio/warehouse;
      /usr/bin/mc policy set public minio/datalake;
      tail -f /dev/null
      "

  ## The Iceberg REST service provides a RESTful interface to interact with Iceberg tables. This catalog uses Postgres for metadata persistence.
  # 1. Base de données pour la persistance des métadonnées du catalogue
  catalog-db:
    image: postgres:15
    container_name: catalog-db
    environment:
      - POSTGRES_USER=iceberg
      - POSTGRES_PASSWORD=iceberg_pass
      - POSTGRES_DB=iceberg_catalog
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iceberg -d iceberg_catalog"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - iceberg_net

  # 2. Le Catalogue REST Iceberg (Configuré pour Postgres)
  rest:
    image: tabulario/iceberg-rest
    container_name: iceberg-rest
    depends_on:
      catalog-db:
        condition: service_healthy
    ports:
      - 8181:8181
    environment:
      # Configuration du Backend SQL
      # - CATALOG_CATALOG-IMPL=org.apache.iceberg.jdbc.JdbcCatalog
      - CATALOG_URI=jdbc:postgresql://catalog-db:5432/iceberg_catalog
      - CATALOG_JDBC_USER=iceberg
      - CATALOG_JDBC_PASSWORD=iceberg_pass
      # Configuration du stockage (MinIO)
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    networks:
      - iceberg_net



## The Trino service is configured to use the Iceberg REST catalog to query Iceberg tables stored in MinIO.
  trino:
    image: trinodb/trino
    container_name: trino
    networks:
      iceberg_net:
    ports:
      - 8080:8080
    depends_on:
      - rest
      - minio
    user: root
    entrypoint: 
      - /bin/sh
      - -c
      - |
        mkdir -p /etc/trino/catalog
        cat <<EOF > /etc/trino/catalog/iceberg.properties
        connector.name=iceberg
        iceberg.catalog.type=rest
        iceberg.rest-catalog.uri=http://iceberg-rest:8181
        iceberg.file-format=PARQUET

        fs.native-s3.enabled=true
        s3.endpoint=http://minio:9000
        s3.aws-access-key=admin
        s3.aws-secret-key=password
        s3.path-style-access=true
        s3.region=us-east-1

        # Use the same IO implementation as Spark
        EOF
        /usr/lib/trino/bin/run-trino


networks:
  iceberg_net: